\Sexpr{set_parent('../../thesis.Rnw')}

\chapter{Constructing a GTFS network}

Here we give a detailed overview of what exactly the
transit network is
(in the previous chapter, we only alluded to it,
and assumed segments where known).

The basic idea of splitting shapes at intersections,
which we get manually, or could potentially
obtain using shape-processing methods.

Some of the slight issues, e.g., missing intersections.
